version: '3'
services:
     redis_db:
        image: "redis"
        volume:
          - ./data:/data
        command: ["redis-server", "--save", "1 1"]  
     node_app:
         build: ./
         image: "nandeepald/visits"
         ports:
           - "8081:8081"
